{
 "title": "Demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 0 },
   "options": {
    "content": "# CG-Automation\nwww.cg-automation.ch"
   }
  },
  {
   "title": "State",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"PlcData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"opcua\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"State\")"
    }
   ]
  },
  {
   "title": "Motor Velocity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 5, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"PlcData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"opcua\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Motor Velocity\")"
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PlcData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"opcua\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Motor Temperature\")"
    }
   ]
  },
  {
   "title": "Motor Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 5, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"PlcData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"opcua\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Motor Temperature\")"
    }
   ]
  }
 ]
}